dependencies:
  - name: influxdb
    version: 0.9.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: influxdb.enabled
    tags:
      - influxdb
  - name: grafana
    version: 1.10.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: grafana.enabled
    tags:
      - grafana
